# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: 

# 订阅链接
- type: subscribe
  options:
    url: 

# 网页模糊抓取
- type: webfuzz
  options:
    url: 

# tg频道抓取
- type: tgchannel
  options:
    channel: 
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: 

# clash格式订阅链接
- type: clash
  options:
    url: 

# 某个网站抓取
- type: web-freessrxyz
  options:
# 订阅链接
- type: subscribe
  options:
    url: https://cherryvpn.net/link/fukXIipnuQeJGSy9?sub=2
# 订阅链接
- type: subscribe1
  options:
    url: https://sub.feifan.zone/d/sub.md
